### ISSUE TITLE
Improve "Meet Someone New"

### ISSUE THREAD

**Issue by mblodorn** [gitconnected/gitconnected-feedback#1]
The feature is listing a lot of ghost users, I think that this should be improved to list only users that meets some requirements, like:

- At least one project
- Recent activity
- Profile picture (?)

What do you guys think?

**Comment by treyhuffine** [comment]
I think that's a great idea @mblodorn. I also would like to make it specific to the logged in user, so I'll see if I can match people with similar interests as well.
