### ISSUE TITLE
Question: Can i generate a PDF?

### ISSUE THREAD

**Issue by naguibihab** [gitconnected/gitconnected-feedback#12]

**Comment by treyhuffine** [comment]
This is actually the next big feature we want to add to the web app. We will allow you create PDF resumes using themes or custom CSS.

At the moment you can do it using the JSON Resume registry. You can learn more about it on[ their website](https://jsonresume.org/getting-started/) or about halfway down the page on the [portfolio API description on gitconnected](https://gitconnected.com/portfolio-api).

**Comment by treyhuffine** [comment]
Apologies for not following, this feature has been added! Once you have an account, you can view your resume and download it as a PDF here - https://gitconnected.com/naguibihab/resume
