### ISSUE TITLE
Team access

### ISSUE THREAD

**Issue by mihan007** [gitconnected/gitconnected-feedback#14]
I like your product. I have IT company, we provide outsource and out staffing services. 

Often tech guys from client side want to overview our developers skills and projects they took part in. It suit your product features. 

Is it possible to have something like company account and link developers to the company? And as final result based on your api we’ll create Team page at our site and some internal tools.

**Comment by treyhuffine** [comment]
Thanks for your feedback, and I really like the idea! I've wanted to add organizations but haven't had the chance to think it out yet.

Unfortunately, I don't think I'll have the time to implement this in the short term, but I'll add it to the roadmap and update you once we're able to prioritize it.

I think a short term solution would be to ask your developers to give you their usernames. Then on your side on the team page, you can fetch the data for each person based on their username.

**Comment by treyhuffine** [comment]
Tracking here - https://github.com/gitconnected/gitconnected-feedback/projects/1#card-51134631
