### ISSUE TITLE
Skills section doesn't show full experience 

### ISSUE THREAD

**Issue by tan1193** [gitconnected/gitconnected-feedback#15]
Skills section doesn't show full experience when I export the profile into PDF file. Can you kindly help me to fix this?

**Comment by treyhuffine** [comment]
Hi Tan, of course happy to help out. Can you describe a little more what issue you're having and what your expected behavior would be?

**Comment by tan1193** [comment]
![Untitled1](https://user-images.githubusercontent.com/13719355/76227339-c11d0900-6251-11ea-90d9-89dbc12939b8.png)

Kindly check the Image attached.

**Comment by treyhuffine** [comment]
Thanks for the visual, that's super helpful. I'm wondering if numbers on the resume would be better than stars. This is one of the tricky things when designing a solution to fit everyone.

I'm actually working on open-sourcing all this code, and I'm wondering if it's best for me to focus on that. Then you'll have complete control and customize however you want. It would also have the ability to share themes in the community. Is that something that would interest you?

**Comment by anexiole** [comment]
hey @treyhuffine , it's very valid that you are open sourcing the code but this is a very good tool and it would be good if it could just show the stats as mentioned by @tan1193 . It's your project at this moment, thus it's your call. If people want different representations, they can lend a hand in putting the alternatives in but for the current moment, there's nothing showing the skill's rating and the number of years but the input template/form is asking for the info.

 Thank you :)

**Comment by treyhuffine** [comment]
Hi @anexiole thanks for the feedback. I definitely want to add this to the UI and also open source the tool. Unfortunately at the moment I'm very busy trying to release another project (https://skilled.dev/), but once it's complete my full focus is going to be back on the resume builder to improve and open source.

**Comment by treyhuffine** [comment]
This has been added! Let me know if you have issues or feedback.
