### ISSUE TITLE
How to add courses I already completed

### ISSUE THREAD

**Issue by aladine** [gitconnected/gitconnected-feedback#16]
I have some certificates of Coursera courses. Which section I should add into my resume builder.

**Comment by treyhuffine** [comment]
Great question @aladine - my original intention was that online courses would go under the education section. What are your thoughts on it?

**Comment by aladine** [comment]
That would be fine. I added my certificate in the education section. It looks like this https://gitconnected.com/aladine/resume

I have an online URL my certificate. It seems the education section doesn't have a field for URL link.

**Comment by treyhuffine** [comment]
Thanks for sharing. I agree the education should contain a URL, that definitely makes sense. I'm gathering some more feedback and will include that when I address it.

**Comment by treyhuffine** [comment]
Thanks for your patience @aladine, this feature has been added. Let me know if you have any feedback or additional questions.

**Comment by treyhuffine** [comment]
Closing for now. Let me know if there are more issues.
