### ISSUE TITLE
Provision to add and display contact number 

### ISSUE THREAD

**Issue by vini46** [gitconnected/gitconnected-feedback#17]
The profile will be perfect and complete if we can have a space to add and display contact/mobile number

**Comment by treyhuffine** [comment]
Thanks @vini46 great feedback! I will put that on our list of fields to add and let you know when it's complete

**Comment by treyhuffine** [comment]
The feature has been added. You can add your phone number here - https://gitconnected.com/settings/phone

It's disabled by default, so you'll also need to turn it on using the resume configuration modal on your profile.

Let me know if you have any questions or additional feedback, and thanks for the help!

**Comment by treyhuffine** [comment]
Closing for now. Let me know if there are more issues.

**Comment by vini46** [comment]
Awesome, thanks mate.. this fix is working fine :)
