### ISSUE TITLE
Un-even Page breaks in Exported PDF

### ISSUE THREAD

**Issue by vini46** [gitconnected/gitconnected-feedback#18]
when profile content is more than one page, an Un-even page break is happening which is cutting the content. 

<img width="856" alt="Screenshot 2020-05-07 at 4 43 41 PM" src="https://user-images.githubusercontent.com/5517009/81288396-322a4280-9082-11ea-9bfc-46e0bf7b4b28.png">

**Comment by treyhuffine** [comment]
Wow, definitely need to figure out how to handle that. Thanks for reporting.

**Comment by treyhuffine** [comment]
I'm seeing on my end that this has been resolved. Going to close out but feel free to re-open if you're seeing other issues.
