### ISSUE TITLE
Default resume.json generated does not work with templates on https://jsonresume.org/themes/

### ISSUE THREAD

**Issue by lincredibleJC** [gitconnected/gitconnected-feedback#20]
Presently, the default resume.json generated does not work on any template on https://jsonresume.org/themes/

![image](https://user-images.githubusercontent.com/22949932/82032746-47c8e900-96ce-11ea-9b09-9ae953ab78e8.png)

The error message shows that the phone field in the generated json is null and has to be manually added into the gist.

It would be good to allow users to add a phone number to their resume on the gitconnected site.
And to prevent this error, we could use a default dummy number instead of a null field.

This bug is related to #17

**Comment by treyhuffine** [comment]
Thanks @lincredibleJC - I totally agree. This is top on my list and should land in production early this week. I'll let you know once it's live.

**Comment by treyhuffine** [comment]
The feature has been added. You can add your phone number here - https://gitconnected.com/settings/phone

It's disabled by default, so you'll also need to turn it on using the resume configuration modal on your profile.

Let me know if you have any questions or additional feedback, and thanks for the help!

**Comment by treyhuffine** [comment]
Closing this for now but let me know if you are still having issues
