### ISSUE TITLE
List all the projects in the API

### ISSUE THREAD

**Issue by ShubhamVerma1811** [gitconnected/gitconnected-feedback#21]
Hey!
In the API response, I see that only featured projects are added.
It would be nice if all our projects where available in the API

**Comment by treyhuffine** [comment]
Thanks for the feedback @ShubhamVerma1811! I'm worried that could be too much because some people have hundreds of projects. Could you give me a little more insight into how you invision using the full list of projects and why you wouldn't want to move them to be featured?

**Comment by ShubhamVerma1811** [comment]
That true, I didn't think of it
I wanted all the projects in API so thay I could display it on my portfolio.
Currently, I can only display featured ones.
I could make all those remaining projects as featured but then I think it would get added to the resume too, which I don't want.

**Comment by treyhuffine** [comment]
That's a great point. The featured projects feature was actually added before the portfolio API/resume. I rolled that over into those new features, but I can see why you would want different projects in each. I'll think on way to better handle this to keep them separate without making it too complex to manage projects for each different aspect. If you have ideas, let me know.

**Comment by treyhuffine** [comment]
I think the fastest solution to this is to just create a new API endpoint for projects so you can pull additional ones that aren't featured. I understand it's not ideal to make 2 API requests, but I don't think it will be good to add all projects to the portfolio API since I think most people are featuring the ones that they want included there.

**Comment by treyhuffine** [comment]
Tracking this here - https://github.com/gitconnected/gitconnected-feedback/projects/1#card-51134572
