### ISSUE TITLE
do not see my project section on pdf

### ISSUE THREAD

**Issue by mayanksharma18** [gitconnected/gitconnected-feedback#22]

**Comment by treyhuffine** [comment]
Have you selected them here? https://gitconnected.com/projects

**Comment by mayanksharma18** [comment]
Yes, i can see them now , forgot to click feature button but i still do not
see my eduction full details and awards on when i view my resume


*Mayank Sharma*
*+918982333823*
*Software Engineer at Seanergy Digital *
*Ex- NTT DATA | Ex- Dell | Amity University*

*LinkedIn
<https://www.linkedin.com/in/mayank-vikesh-kumar-sharma-73978270/> | GitHub
<https://github.com/mayanksharma18>*

**Comment by treyhuffine** [comment]
Thanks for the details. What is missing from the education that expected to appear?

We're working for design to show awards and volunteer on the resume, and we'll add those ASAP.

**Comment by mayanksharma18** [comment]
Activities

*Mayank Sharma*
*+918982333823*
*Software Engineer at Seanergy Digital *
*Ex- NTT DATA | Ex- Dell | Amity University*

*LinkedIn
<https://www.linkedin.com/in/mayank-vikesh-kumar-sharma-73978270/> | GitHub
<https://github.com/mayanksharma18>*

**Comment by treyhuffine** [comment]
Thanks for the feedback! This is now being tracked in another issue, so closing this out
