### ISSUE TITLE
 Activities and societies section in Education

### ISSUE THREAD

**Issue by mayankseanergy12** [gitconnected/gitconnected-feedback#23]
I have added Activities and societies section in Education and Honors and awards section too
but i can't see on pdf .

https://gitconnected.com/mayanksharma18/resume

**Comment by treyhuffine** [comment]
Thanks for letting me know, we're working that incorporate those into the design and will get it released as soon as we can. I'll leave this issue open and update as soon as we have this fixed.

**Comment by treyhuffine** [comment]
Sorry for the delay, these have been added!
