### ISSUE TITLE
Can't add alternate email

### ISSUE THREAD

**Issue by VicenteQuesadaDeb** [gitconnected/gitconnected-feedback#24]
I would like to change my email, but I can't modify either add another email on my profile.
Help!

**Comment by treyhuffine** [comment]
Hi @VicenteQuesadaDeb thanks for reaching out. So when gitconnected was originally created, it was more tightly coupled GitHub but we've been moving away from that. Emails are still one of the things that more coupled and it looks for emails from GitHub to populate your list. I know this is unfortunate, but the easiest way to do it at the moment is to add an email to github and then sign out and back in to gitconnected.com and it should appear there.
