### ISSUE TITLE
No UI for Interest and Language Input

### ISSUE THREAD

**Issue by itsmanojb** [gitconnected/gitconnected-feedback#25]
The API response for `https://gitconnected.com/v1/portfolio/{username}` has following two properties,
```
{
    ...
    interests: []
    languages: []
    ...
}
```

But in https://gitconnected.com/ there's no such UI where one can put the interest or languages.
Even if there are, they are hard to find. 
![image](https://user-images.githubusercontent.com/11155266/86154868-468a3900-bb21-11ea-81d8-c99bca15b1d9.png)

**Comment by KVikram** [comment]
@treyhuffine This is much needed feature as it will complete JSON resume schema.

**Comment by treyhuffine** [comment]
Hi @itsmanojb @KVikram thanks for the feedback. I had initially left that off because I wasn't sure if people used it and didn't want to make the UI too populated and difficult to parse. I'll work on that since you all need it. I'll reply here once it's ready.

**Comment by treyhuffine** [comment]
This has been added. Let me know if you notice any issues or have additional feedback.
