### ISSUE TITLE
User should be able to download the Resume in Word format

### ISSUE THREAD

**Issue by ninad458** [gitconnected/gitconnected-feedback#27]
Can I get the word file please. The resume doesn't show project description.
You have no control over the formatting. Some text of one project lies on the second page.

**Comment by treyhuffine** [comment]
Thanks for the feedback. I think the goal is to actually replace Word documents, so I'm not sure it's something on the roadmap to support at the moment. 

We will definitely fix the styling issues though for the current resumes and also plan to add theming options.
