### ISSUE TITLE
Awards & Publications Sections are missing in Resume

### ISSUE THREAD

**Issue by itsharsh** [gitconnected/gitconnected-feedback#29]

**Comment by treyhuffine** [comment]
Thanks for the feedback, we'll work on getting this added

**Comment by SamDuffield** [comment]
+1 for this!

**Comment by treyhuffine** [comment]
Sorry for the delay, this has been added! I'm putting a lot of time into this project now, and you should continue to see some big improvements. I will also be open sourcing everything next year so it can move much quicker and enable the community to build their own templates and solutions.

Let me know if you see any issues or have feedback.
