### ISSUE TITLE
Cannot sign up

### ISSUE THREAD

**Issue by funzeye** [gitconnected/gitconnected-feedback#32]
When I try to sign up and connect with Github I get the following.
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

I got email from Github to confirm the linking worked - but whenever I click sign up/log in button I get the above 500 error.

from github
"A third-party OAuth application (gitconnected) with read:org, read:user, and user:email scopes was recently authorized to access your account."

**Comment by treyhuffine** [comment]
Thanks for letting me know, I'll check the server logs and figure out what the issue is.

**Comment by treyhuffine** [comment]
Is funzeye the username you tried to register with?

**Comment by funzeye** [comment]
yes

**Comment by treyhuffine** [comment]
I wasn't able to find anything in the logs, and this is the only report I've been alerted on. I think the only way to solve it is to hold a debug session sometime if you're interested. Feel free to reach out to me if you want to!
