### ISSUE TITLE
Pagination, git connected profile, and resume file name displayed

### ISSUE THREAD

**Issue by NoelHG** [gitconnected/gitconnected-feedback#33]
Basically there's some metadata being shown that doesn't seem intended. 

Using Google Chrome, I am seeing pagination with the gitconnected profile link at the bottom. Not sure if intended. The gitconnected resume link seems unnecessary.

In the PDF, the file name (full name + "resume") and download date are shown at the top of every page. Not sure if intended, or needed.

**Comment by treyhuffine** [comment]
Hi @NoelHG - can you send a screen shot of what you're seeing or DM me? I think this may be internal computer settings

**Comment by treyhuffine** [comment]
Here's how mine exports
[Trey Huffine Resume.pdf](https://github.com/gitconnected/gitconnected-feedback/files/5672950/Trey.Huffine.Resume.pdf)

**Comment by NoelHG** [comment]
Wow, you're absolutely correct. I hadn't noticed how terrible the defaults were on both my Chrome and Firefox.
