### ISSUE TITLE
Upload existed JSON Resume file to fill my resume!

### ISSUE THREAD

**Issue by lisovskyvlad** [gitconnected/gitconnected-feedback#34]
Good day everyone! 

I'd created in past my resume using json-resume format in past before few minutes ago I discovered gitconnected.com.

Unfortunately, I don't see a feature to upload the file to pre-full my profile. 

Could you consider that as a feature in future? Or may I just have missed it ;(

**Comment by treyhuffine** [comment]
Hi @lisovskyvlad this is very high on the list of improvements, but it doesn't exist yet. I'm hoping to have integrated very soon, and I'll respond here when it's available.

**Comment by data219** [comment]
:+1: That was the first feature I was looking for after finding gitconnected via the json resume homepage and already having started at my json resume. That feature would be very appreciated!

**Comment by lisovskyvlad** [comment]
Thanks for updates! looking forward!
