### ISSUE TITLE
Bug | Awards not sorted by date

### ISSUE THREAD

**Issue by isopropylcyanide** [gitconnected/gitconnected-feedback#38]
Refer https://gitconnected.com/isopropylcyanide/resume

**Configuration:**
![image](https://user-images.githubusercontent.com/12872673/107277692-c777be80-6a7a-11eb-940a-354c79883507.png)

**Actual output that doesn't match expected** 
![image](https://user-images.githubusercontent.com/12872673/107277651-b9c23900-6a7a-11eb-8df2-fc68f227087b.png)

Notice, 2020 comes before 2019.

**Comment by treyhuffine** [comment]
Thanks for the bug report! This should be fixed. If you find any additional issues, let me know.

**Comment by isopropylcyanide** [comment]
This is fixed. Thanks for the quick action.
