### ISSUE TITLE
Ability to edit email addresses

### ISSUE THREAD

**Issue by city41** [gitconnected/gitconnected-feedback#4]
Hey gitconnected is pretty cool! Thanks for building it.

It'd be nice if we could edit the email addresses in our profile. You guys managed to find an ancient email address of mine that is no longer active, would like to delete it.

**Comment by treyhuffine** [comment]
Agreed, that's essential. I'll look at adding that for you. Sorry for the late feedback, I didn't realize people were actively using our issues already :)
