### ISSUE TITLE
Incorrect date ranges displayed in PDF and Order of employment is incorrect. 

### ISSUE THREAD

**Issue by Sergio16T** [gitconnected/gitconnected-feedback#41]
1)  PDF - shows end date Jan 2021 for end date that should be February 2021.
2) PDF - The start date for newest role should be Feb 2021 but shows January. 
3) The roles are not in chronological order.  Most recent role should be at the top in displayed order followed by the contract roles in chronological order.
       -- would be a great feature add to be able to customize the order as well. Select which role is at top etc. 

Thank you for your help!

**Comment by treyhuffine** [comment]
Thanks @Sergio16T! This should be fixed now. Let me know if you notice any other issues.
