### ISSUE TITLE
Featured blog posts

### ISSUE THREAD

**Issue by city41** [gitconnected/gitconnected-feedback#5]
It'd be nice if along with projects, we could feature blog posts and articles we've written.

**Comment by treyhuffine** [comment]
Thanks for the feedback @city41! We now have a posting feature. I really like the idea of being able to feature articles and blogs posts as well. I'll add that to our feature list pipeline.

**Comment by treyhuffine** [comment]
@city41 sorry for the very long delay on getting back to you, but this feature does exist in the web app now. Thanks a bunch for getting the idea out there!
