### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by SkyzohKey** [gitconnected/gitconnected-feedback#6]
Hey guys,

Would it be possible to expose a public GraphQL API so that I could build a mobile client ? 

Thanks in advance ! :)

**Comment by treyhuffine** [comment]
Hey @SkyzohKey, we're very excited about your interest! We currently utilize a REST API if you're interested in building around that. I would be happy to get you some docs. We plan to build a GraphQL API in the future, but the start date for that is unknown.

Our authentication scheme is only built for web right now, so to start, you may only be able build views around public routes - viewing profiles, reading posts, etc.

Let me know what you think!

**Comment by SkyzohKey** [comment]
@treyhuffine I can also work with a REST api of course, will just need some redux/redux-thunk/fetch love, :p

**Comment by treyhuffine** [comment]
Apologies for the very long delay here @SkyzohKey - we're beta testing our first API release. It's a user's profile wrapped into a JSON résumé API. If follows the patter GET gitconnected.com/v1/api/resume/{username}

So mine would be - [https://gitconnected.com/v1/api/resume/treyhuffine](https://gitconnected.com/v1/api/resume/treyhuffine)
