### ISSUE TITLE
New year banner

### ISSUE THREAD

**Issue by Trewaters** [gitconnected/gitconnected-feedback#77]
Hi, I logged in for the new year and saw a banner for free courses in 2023. Time to update last years notices.

Here is what I saw
![gitconnected-Screenshot 2024-01-20 122145](https://github.com/gitconnected/gitconnected-feedback/assets/7051102/6b8a09fb-ab6f-48dd-a473-2d5f73ded300)

**Comment by treyhuffine** [comment]
Thanks Tre, it's been updated to be indefinitely free! I really appreciate you calling it out.

It's been ages, I hope you're doing well!
