### ISSUE TITLE
Import an initial profile

### ISSUE THREAD

**Issue by tjdavis3** [gitconnected/gitconnected-feedback#9]
It would be helpful to be able to import an initial profile.  Either something like an API integration with things like linked-in, or even the ability to import an initial jsonresume if one has already been created on another platform.

**Comment by treyhuffine** [comment]
Really great idea @tjdavis3 - I was trying to think of the best way to reduce the friction of creating a profile, and this makes a lot of sense. I'll try to get this prioritized as quickly as I can, and I'll let you know when it's ready.

If you have any other feedback, create an issue anytime. It's always incredibly helpful. :)

**Comment by tjdavis3** [comment]
Any movement on this?

**Comment by treyhuffine** [comment]
Unfortunately not yet. I'm overloaded at the moment, and I still haven't figured out the best way to move on this. However, I plan to open source the entire project sometime before the end of 2020, so it should be much easier to build solutions with the community.

**Comment by treyhuffine** [comment]
Sorry I forgot to update this - you can import JSON Resume now, and I'm looking into how to pull a LinkedIn profile

**Comment by tjdavis3** [comment]
I ran across it on the site and was able to import my resume.  Thanks.  FWIW, I initially created my jsonresume from LinkedIn using the tools on jsonresume.org (I think).
